import { describe, expect, it } from "vitest";
import { inferMonthlyIntervalFromCronExpression } from "./task-schedule-cron";

describe("inferMonthlyIntervalFromCronExpression", () => {
  it("parses monthly cron generated by the dialog", () => {
    expect(inferMonthlyIntervalFromCronExpression("38 9 15 * *")).toBe(1);
    expect(inferMonthlyIntervalFromCronExpression("38 9 15 1,3,5,7,9,11 *")).toBe(2);
    expect(inferMonthlyIntervalFromCronExpression("38 9 15 6 *")).toBeNull();
  });

  it("does not confuse minute or daily cron with monthly schedules", () => {
    expect(inferMonthlyIntervalFromCronExpression("0,2,4,6,8 * * * *")).toBeNull();
    expect(inferMonthlyIntervalFromCronExpression("38 * * * *")).toBeNull();
    expect(inferMonthlyIntervalFromCronExpression("38 9 * * *")).toBeNull();
    expect(inferMonthlyIntervalFromCronExpression("* * * * *")).toBeNull();
  });
});
