import { describe, expect, it } from "vitest";
import { inferCronPeriodFromExpression, inferFixedIntervalFromCronExpression, inferMonthlyIntervalFromCronExpression } from "./task-schedule-cron";

describe("inferFixedIntervalFromCronExpression", () => {
  it("parses standard stepped cron expressions", () => {
    expect(inferFixedIntervalFromCronExpression("*/2 * * * *")).toEqual({
      repeatEvery: 2,
      repeatUnit: "minutes",
    });
    expect(inferFixedIntervalFromCronExpression("15 */3 * * *")).toEqual({
      repeatEvery: 3,
      repeatUnit: "hours",
    });
  });

  it("keeps supporting equivalent enumerated cron expressions", () => {
    expect(inferFixedIntervalFromCronExpression("0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * *")).toEqual({
      repeatEvery: 2,
      repeatUnit: "minutes",
    });
  });
});

describe("inferMonthlyIntervalFromCronExpression", () => {
  it("parses monthly cron generated by the dialog", () => {
    expect(inferMonthlyIntervalFromCronExpression("38 9 15 * *")).toBe(1);
    expect(inferMonthlyIntervalFromCronExpression("38 9 15 1,3,5,7,9,11 *")).toBe(2);
    expect(inferMonthlyIntervalFromCronExpression("38 9 15 6 *")).toBeNull();
  });

  it("does not confuse minute or daily cron with monthly schedules", () => {
    expect(inferMonthlyIntervalFromCronExpression("0,2,4,6,8 * * * *")).toBeNull();
    expect(inferMonthlyIntervalFromCronExpression("38 * * * *")).toBeNull();
    expect(inferMonthlyIntervalFromCronExpression("38 9 * * *")).toBeNull();
    expect(inferMonthlyIntervalFromCronExpression("* * * * *")).toBeNull();
  });
});

describe("inferCronPeriodFromExpression", () => {
  it("chooses the smallest matching period for common 5-field cron expressions", () => {
    expect(inferCronPeriodFromExpression("*/2 * * * *")).toBe("minute");
    expect(inferCronPeriodFromExpression("0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * *")).toBe("minute");
    expect(inferCronPeriodFromExpression("15 */3 * * *")).toBe("hour");
    expect(inferCronPeriodFromExpression("15 9 * * 1,3,5")).toBe("week");
    expect(inferCronPeriodFromExpression("15 9 15 * *")).toBe("month");
    expect(inferCronPeriodFromExpression("15 9 15 1,7 *")).toBe("month");
    expect(inferCronPeriodFromExpression("* * * * *")).toBe("minute");
  });
});
